DROP INDEX IF EXISTS idx_otp_tx_email_created_at;
ALTER TABLE IF EXISTS otp_tx DROP COLUMN IF EXISTS last_sent_at;
ALTER TABLE IF EXISTS otp_tx DROP COLUMN IF EXISTS used_at;
ALTER TABLE IF EXISTS otp_tx DROP COLUMN IF EXISTS attempts;
